apiVersion: v1

kind: Service
metadata:
  name: feed-svc
  labels:
    run: feed-svc
spec:
  selector:
    app: feed-svc
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 3000
  type: ClusterIP

